-- 2022년 1월 판매 데이터 기준
-- 저자별, 카테고리별 매출액
-- 저자 아이디, 저자명, 카테고리, 매출액 리스트 출력
-- 결과: 저자 아이디 오름차순, 카테고리 내림차순 정렬
SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(PRICE*SALES) AS TOTAL_SALES
FROM BOOK
JOIN AUTHOR
    ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
JOIN BOOK_SALES
    ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE BOOK_SALES.SALES_DATE LIKE '2022-01-%'
GROUP BY BOOK.AUTHOR_ID, BOOK.CATEGORY
ORDER BY BOOK.AUTHOR_ID, BOOK.CATEGORY DESC;