SELECT ED.ID
FROM ECOLI_DATA AS ED
INNER JOIN (SELECT ED.ID
            FROM ECOLI_DATA AS ED
            INNER JOIN (SELECT ID
                        FROM ECOLI_DATA
                        WHERE PARENT_ID IS NULL) AS FIRST
            ON ED.PARENT_ID = FIRST.ID) AS SECOND
ON ED.PARENT_ID = SECOND.ID
ORDER BY ID;

# 1세대
# SELECT ID
# FROM ECOLI_DATA
# WHERE PARENT_ID IS NULL
# ORDER BY ID;

# 2세대
# SELECT ED.ID
# FROM ECOLI_DATA AS ED
# INNER JOIN (SELECT ID
#             FROM ECOLI_DATA
#             WHERE PARENT_ID IS NULL) AS FIRST
# ON ED.PARENT_ID = FIRST.ID
# ORDER BY ID;


