SELECT COMPANY.CAR_ID,
       COMPANY.CAR_TYPE,
       ROUND(COMPANY.DAILY_FEE * 30 * (1 - (DISCOUNT.DISCOUNT_RATE / 100))) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS COMPANY
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DISCOUNT
  ON COMPANY.CAR_TYPE = DISCOUNT.CAR_TYPE
 AND DISCOUNT.DURATION_TYPE = '30일 이상'
WHERE (COMPANY.CAR_TYPE = '세단' OR COMPANY.CAR_TYPE = 'SUV')
  AND COMPANY.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
  )
HAVING FEE >= 500000
   AND FEE < 2000000
ORDER BY FEE DESC, COMPANY.CAR_TYPE ASC, COMPANY.CAR_ID DESC
;
