-- 중고거래게시물 3건 이상 등록
-- 사용자 ID, 닉네임, 전체주소, 전화번호 조회
-- 전체 주소는 시도로명 주소, 상세 주소
-- 전화번호는 하이픈 문자열로 구분
-- 회원 ID 기준 내림차순 정렬
SELECT USERS.USER_ID, USERS.NICKNAME, CONCAT(USERS.CITY, ' ', USERS.STREET_ADDRESS1, ' ', USERS.STREET_ADDRESS2) AS 전체주소, 
CONCAT(SUBSTR(USERS.TLNO, 1, 3), '-', SUBSTR(USERS.TLNO, 4, 4), '-', SUBSTR(USERS.TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_USER AS USERS
JOIN USED_GOODS_BOARD AS BOARD
ON USERS.USER_ID = BOARD.WRITER_ID
GROUP BY BOARD.WRITER_ID
HAVING COUNT(BOARD.BOARD_ID) >= 3 
ORDER BY USERS.USER_ID DESC;