SELECT INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS, ROUND(AVG(REV.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS INFO
INNER JOIN REST_REVIEW AS REV
ON INFO.REST_ID = REV.REST_ID
WHERE INFO.ADDRESS LIKE '서울%'
GROUP BY INFO.REST_ID
ORDER BY AVG(REV.REVIEW_SCORE) DESC, INFO.FAVORITES DESC; 
