-- 대여 시작일 기준 2022-08~2022-10까지
-- 해당 기간 동안의 월별 자동차 ID별
-- 총 대여 횟수(RECORDS) 5회 이상
-- 월 기준 오름차순, 자동차 ID 기준 내림차순
-- 특정 월의 총 대여 횟수가 0이면 결과에서 제외
SELECT DATE_FORMAT(START_DATE, '%m') AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
AND CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5)
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC;