SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR,
       (MAX_YEAR.MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV,
       ED.ID
FROM ECOLI_DATA AS ED
INNER JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
           MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) AS MAX_YEAR
ON YEAR(ED.DIFFERENTIATION_DATE) = MAX_YEAR.YEAR
ORDER BY YEAR, YEAR_DEV;
