SELECT FIR.FLAVOR
FROM FIRST_HALF AS FIR
INNER JOIN ICECREAM_INFO AS ICE
ON ICE.FLAVOR = FIR.FLAVOR
WHERE FIR.TOTAL_ORDER >= 3000
AND ICE.INGREDIENT_TYPE = 'fruit_based'
ORDER BY FIR.TOTAL_ORDER DESC;